name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    name: Python ${{ matrix.python-version }} sample
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
        run:
          python3 -m venv venv 
          . ./venv/bin/activate
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          uvicorn main:app --reload
      - name: Run a one-line script
        run: echo Hello, world!